export const products = [
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "this",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 200,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 89,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 0,
    distributor: "eccent components private limited",
    featured: false,
  },
  {
    _id: "099igf09nv0934nv0984n3g",
    name: "1/4 Inch Anti Corrosion Teflon Acid Resistant Solenoid Valve NC",
    category: "Valve",
    price: 249.99,
    qty: 8,
    distributor: "eccent components private limited",
    featured: false,
  },
];
